name = "plantsage"
compatibility_date = "2024-01-18"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install && npm run build"

[build.upload]
format = "directory"

[site]
bucket = ".next"

[env.production]
pages_build_output_dir = ".next"

[[routes]]
pattern = "/api/.*"
zone_name = "plantsage.pages.dev"
