name = "plantsage"
compatibility_date = "2024-01-18"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./out"

[build]
command = "npm install && npm run build"
output_directory = "/out"

[build.upload]
format = "service-worker"

[[build.environment]]
name = "production"
runtime = "edge"

[env.production]
workers_dev = true
